### ISSUE TITLE
Good old times

### ISSUE THREAD

**Issue by jojo12** [slabbi/Sinclair-ZX-Spectrum#1]
Hallo Stephan, 
du erinnerst mich an meinen ersten Computer, den ZX Spectrum! War so ein toller Einstieg!
Danke dass Du Dich immer noch für uddeIM engagierst, obwohl Du selber schon lange nach WP gewechselt hast!
Jojo Murer

**Comment by slabbi** [comment]
Hallo,
das ist war. Ich habe durch ein Z80 Projekt jetzt nach 40 Jahren wieder in Z80 Assembler programmieren müssen. Da habe ich die Gelegenheit genutzt ein paar alte Programme abzulegen.
Ich wäre auch noch bei Joomla, wenn nicht jede neue Version etliche Erweiterungen unbrauchbar machen würde und man praktisch wöchentlich mit nichts anderem beschäftigt ist, als seine Website am Laufen zu halten.
Stephan
